export const OrderStatus = {
  WAIT: 'WAIT',
  ACCEPT: 'ACCEPT',
  DELIVERY: 'DELIVERY',
  DELIVERED: 'DELIVERED',
  RECEIVED: 'RECEIVED',
  REFUNDING: 'REFUNDING',
  REFUNDED: 'REFUNDED',
  CANCEL: 'CANCEL',
  FAIL: 'FAIL',
  FINISH: 'FINISH',
}
